version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: api_postgres_ejercicio
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data_ejercicio:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - api_network_ejercicio
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: api_node_ejercicio
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - api_network_ejercicio
    volumes:
      - ./src:/app
      - /app/node_modules
    command: npm run dev

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: api_pgadmin_ejercicio
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    networks:
      - api_network_ejercicio

volumes:
  pg_data_ejercicio:

networks:
  api_network_ejercicio:
    driver: bridge